version: '3.9'

services:
  server:
    pull_policy: build
    build: .
    image: server
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      replicas: 5
    networks:
      - pubsub

  redis:
    image: redis:latest
    restart: always
    command: redis-server
    volumes:
      - redis:/var/lib/redis
    ports:
      - 6379:6379
    networks:
      - pubsub
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
  
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    networks:
      - pubsub
    ports:
      - "3000:3000"

volumes:
  redis:


networks:
  pubsub:
    driver: bridge
